name: rightsstatements
url: //h2481931.stratoserver.net:4000
canonical_url: //rightsstatements.org
markdown: kramdown
kramdown:
  parse_block_html: true
highlighter: rouge
excerpt_separator: <!--more-->
exclude: [scripts]
defaults:
  -
    scope:
      path: "en"
    values:
      lang: "en"
      categories: ["en"]
      iso_name: "English"
  -
    scope:
      path: "de"
    values:
      lang: "de"
      categories: ["de"]
      iso_name: "Deutsch"
  -
    scope:
      path: "es"
    values:
      lang: "es"
      categories: ["es"]
      iso_name: "Español"
  -
    scope:
      path: "et"
    values:
      lang: "et"
      categories: ["et"]
      iso_name: "Eesti"
  -
    scope:
      path: "fi"
    values:
      lang: "fi"
      categories: ["fi"]
      iso_name: "Suomi"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"
      categories: ["fr"]
      iso_name: "Français"
  -
    scope:
      path: "hi"
    values:
      lang: "hi"
      categories: ["hi"]
      iso_name: "हिन्दी"
  -
    scope:
      path: "pl"
    values:
      lang: "pl"
      categories: ["pl"]
      iso_name: "Polski"
author: rightsstatements.org
permalink: /:categories/:year/:month/:slug.html
plugins:
  - jekyll-paginate
  - jekyll-feed
paginate: 10
paginate_path: "/en/blog/:num/"
default_language: en
languages_enabled: yes
rights_data_version: 1.0
white_paper_tech_version: 180117requirements_for_the_technical_infrastructure_for_standardized_international_rights_statements_v1.2.1.pdf
white_paper_rs_version: 180531recommendations_for_standardized_international_rights_statements_v1.2.2.pdf
policy_editorial_version: 170612rs_editorial_policy.pdf
policy_translation_version: 170612rs_translation_policy.pdf
font_css_url: https://cloud.typography.com/7197296/6463212/css/fonts.css
