name: rightsstatements
url: //h2481931.stratoserver.net:4000
canonical_url: //rightsstatements.org
markdown: kramdown
kramdown:
  parse_block_html: true
highlighter: rouge
excerpt_separator: <!--more-->
exclude: [scripts]
defaults:
  -
    scope:
      path: "en"
    values:
      lang: "en"
      iso_name: "English"
default_language: en
languages_enables: no
rights_app_server: //h2481931.stratoserver.net:9001
rights_data_version: 1.0
